const exercise = [
  // Chest Exercises (Difficulty 1-5)
  { name: "Incline Push-ups", difficulty: 1, bodyPart: "Chest", id: "45D" },
  { name: "Chest Fly", difficulty: 2, bodyPart: "Chest", id: "34C" },
  { name: "Push-ups", difficulty: 3, bodyPart: "Chest", id: "12A" },
  { name: "Decline Push-ups", difficulty: 4, bodyPart: "Chest", id: "56E" },
  { name: "Bench Press", difficulty: 4, bodyPart: "Chest", id: "23B" },
  { name: "Cable Crossover", difficulty: 2, bodyPart: "Chest", id: "78H" },
  { name: "Dumbbell Pullover", difficulty: 3, bodyPart: "Chest", id: "90J" },
  { name: "Pec Deck", difficulty: 3, bodyPart: "Chest", id: "67M" },
  { name: "Wide Grip Push-ups", difficulty: 4, bodyPart: "Chest", id: "34N" },
  { name: "Clap Push-ups", difficulty: 5, bodyPart: "Chest", id: "45K" },
  {
    name: "Incline Dumbbell Press",
    difficulty: 4,
    bodyPart: "Chest",
    id: "23F",
  },
  { name: "Chest Dips", difficulty: 5, bodyPart: "Chest", id: "12L" },
  { name: "Machine Chest Press", difficulty: 3, bodyPart: "Chest", id: "89Q" },
  { name: "Diamond Push-ups", difficulty: 5, bodyPart: "Chest", id: "78R" },
  { name: "Archer Push-ups", difficulty: 5, bodyPart: "Chest", id: "56Z" },

  // Back Exercises (Difficulty 2-5)
  { name: "Superman Exercise", difficulty: 2, bodyPart: "Back", id: "90I" },
  { name: "Bent-over Rows", difficulty: 3, bodyPart: "Back", id: "78G" },
  { name: "Reverse Fly", difficulty: 3, bodyPart: "Back", id: "01J" },
  { name: "Lat Pulldowns", difficulty: 4, bodyPart: "Back", id: "89H" },
  { name: "Pull-ups", difficulty: 5, bodyPart: "Back", id: "67F" },
  { name: "Dead Hangs", difficulty: 2, bodyPart: "Back", id: "34T" },
  { name: "T-Bar Rows", difficulty: 4, bodyPart: "Back", id: "12U" },
  { name: "Good Mornings", difficulty: 3, bodyPart: "Back", id: "45L" },
  { name: "Seated Cable Rows", difficulty: 3, bodyPart: "Back", id: "90K" },
  {
    name: "Single-arm Dumbbell Rows",
    difficulty: 4,
    bodyPart: "Back",
    id: "78S",
  },
  { name: "Inverted Rows", difficulty: 3, bodyPart: "Back", id: "56X" },
  { name: "Chin-ups", difficulty: 5, bodyPart: "Back", id: "34V" },
  { name: "Kettlebell Swings", difficulty: 4, bodyPart: "Back", id: "67Y" },
  { name: "Landmine Rows", difficulty: 4, bodyPart: "Back", id: "23W" },
  { name: "Barbell Shrugs", difficulty: 3, bodyPart: "Back", id: "12R" },

  // Arm Exercises (Difficulty 2-5)
  { name: "Bicep Curls", difficulty: 2, bodyPart: "Arms", id: "12K" },
  { name: "Hammer Curls", difficulty: 2, bodyPart: "Arms", id: "34M" },
  {
    name: "Overhead Tricep Extensions",
    difficulty: 3,
    bodyPart: "Arms",
    id: "45N",
  },
  { name: "Tricep Dips", difficulty: 3, bodyPart: "Arms", id: "23L" },
  { name: "Concentration Curls", difficulty: 4, bodyPart: "Arms", id: "56O" },
  { name: "Preacher Curls", difficulty: 3, bodyPart: "Arms", id: "78P" },
  { name: "Zottman Curls", difficulty: 3, bodyPart: "Arms", id: "12Q" },
  {
    name: "Incline Dumbbell Curls",
    difficulty: 4,
    bodyPart: "Arms",
    id: "67A",
  },
  {
    name: "Cable Tricep Pushdowns",
    difficulty: 2,
    bodyPart: "Arms",
    id: "90T",
  },
  { name: "Skull Crushers", difficulty: 5, bodyPart: "Arms", id: "23U" },
  { name: "Reverse Curls", difficulty: 3, bodyPart: "Arms", id: "34V" },
  {
    name: "Close Grip Bench Press",
    difficulty: 4,
    bodyPart: "Arms",
    id: "56W",
  },
  { name: "Rope Hammer Curls", difficulty: 3, bodyPart: "Arms", id: "78X" },
  {
    name: "Overhead Cable Extensions",
    difficulty: 3,
    bodyPart: "Arms",
    id: "45Y",
  },
  { name: "Spider Curls", difficulty: 4, bodyPart: "Arms", id: "89Z" },

  // Leg Exercises (Difficulty 2-5)
  { name: "Squats", difficulty: 2, bodyPart: "Legs", id: "67P" },
  { name: "Lunges", difficulty: 3, bodyPart: "Legs", id: "78Q" },
  { name: "Step-Ups", difficulty: 3, bodyPart: "Legs", id: "01T" },
  { name: "Leg Press", difficulty: 4, bodyPart: "Legs", id: "90S" },
  { name: "Deadlifts", difficulty: 5, bodyPart: "Legs", id: "89R" },
  { name: "Goblet Squats", difficulty: 3, bodyPart: "Legs", id: "23V" },
  {
    name: "Bulgarian Split Squats",
    difficulty: 5,
    bodyPart: "Legs",
    id: "34X",
  },
  { name: "Calf Raises", difficulty: 2, bodyPart: "Legs", id: "45Y" },
  { name: "Glute Bridges", difficulty: 2, bodyPart: "Legs", id: "67Z" },
  { name: "Box Jumps", difficulty: 4, bodyPart: "Legs", id: "12U" },
  { name: "Hip Thrusts", difficulty: 3, bodyPart: "Legs", id: "78T" },
  { name: "Barbell Front Squats", difficulty: 5, bodyPart: "Legs", id: "90W" },
  { name: "Leg Curls", difficulty: 3, bodyPart: "Legs", id: "56T" },
  { name: "Sumo Deadlifts", difficulty: 4, bodyPart: "Legs", id: "12R" },
  { name: "Wall Sits", difficulty: 2, bodyPart: "Legs", id: "34A" },

  // Cardio Exercises (Difficulty 1-5)
  { name: "Jumping Jacks", difficulty: 1, bodyPart: "Cardio", id: "23V" },
  { name: "High Knees", difficulty: 2, bodyPart: "Cardio", id: "34W" },
  { name: "Mountain Climbers", difficulty: 3, bodyPart: "Cardio", id: "45X" },
  { name: "Burpees", difficulty: 4, bodyPart: "Cardio", id: "12U" },
  { name: "Sprints", difficulty: 5, bodyPart: "Cardio", id: "56Y" },
  { name: "Jump Rope", difficulty: 3, bodyPart: "Cardio", id: "67Z" },
  { name: "Stair Climbing", difficulty: 3, bodyPart: "Cardio", id: "78C" },
  { name: "Rowing Machine", difficulty: 4, bodyPart: "Cardio", id: "90B" },
  { name: "Cycling", difficulty: 3, bodyPart: "Cardio", id: "34A" },
  { name: "Battle Ropes", difficulty: 4, bodyPart: "Cardio", id: "12T" },
  { name: "Shadow Boxing", difficulty: 2, bodyPart: "Cardio", id: "45R" },
  { name: "Treadmill Running", difficulty: 4, bodyPart: "Cardio", id: "23U" },
  { name: "Rowing", difficulty: 5, bodyPart: "Cardio", id: "56A" },
  { name: "Swimming", difficulty: 4, bodyPart: "Cardio", id: "78G" },
];

export { exercise };
